Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2018-09, with the labels that each got.

#2 Add tnozicka
  OWNERS
Labels: size/XS

#5 move copy to library-go
  glide.lock
  pkg/operator/sync_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/register.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/assets/assets.go
  vendor/github.com/openshift/library-go/pkg/assets/template.go
  vendor/github.com/openshift/library-go/pkg/config/helpers/client.go
  vendor/github.com/openshift/library-go/pkg/config/helpers/config_refs.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
Labels: approved, size/XL

#6 make verify pass
  .gitignore
  Makefile
  hack/build-cross.sh
  hack/build-go.sh
  hack/build-images.sh
  hack/build-rpms.sh
  hack/cherry-pick.sh
  hack/import-restrictions.json
  hack/move-upstream.sh
  hack/push-release.sh
  hack/test-go.sh
  hack/update-codegen.sh
  hack/update-generated-bindata.sh
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
  hack/verify-imports.sh
  hack/verify-upstream-commits.sh
  pkg/operator/start_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XXL

#9 typo in image name
  Makefile
Labels: approved, lgtm, size/XS

#8 update to flat updatepayload structure
  Dockerfile
  bindata/v3.11.0/openshift-apiserver/apiserver-clusterrolebinding.yaml
  bindata/v3.11.0/openshift-apiserver/cm.yaml
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  bindata/v3.11.0/openshift-apiserver/deployment.yaml
  bindata/v3.11.0/openshift-apiserver/ns.yaml
  bindata/v3.11.0/openshift-apiserver/public-info-role.yaml
  bindata/v3.11.0/openshift-apiserver/public-info-rolebinding.yaml
  bindata/v3.11.0/openshift-apiserver/public-info.yaml
  bindata/v3.11.0/openshift-apiserver/sa.yaml
  bindata/v3.11.0/openshift-apiserver/svc.yaml
  hack/update-generated-bindata.sh
  manifests/00_clusteropenshiftapiserveroperator_00_namespace.yaml
  manifests/00_clusteropenshiftapiserveroperator_01_config.crd.yaml
  manifests/00_clusteropenshiftapiserveroperator_02_config.yaml
  manifests/00_clusteropenshiftapiserveroperator_03_configmap.yaml
  manifests/00_clusteropenshiftapiserveroperator_04_roles.yaml
  manifests/00_clusteropenshiftapiserveroperator_05_serviceaccount.yaml
  manifests/00_clusteropenshiftapiserveroperator_06_deployment.yaml
  manifests/install/operator.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#14 fix whitespace
  manifests/00_clusteropenshiftapiserveroperator_00_namespace.yaml
  manifests/00_clusteropenshiftapiserveroperator_01_config.crd.yaml
  manifests/00_clusteropenshiftapiserveroperator_02_config.yaml
  manifests/00_clusteropenshiftapiserveroperator_03_configmap.yaml
  manifests/00_clusteropenshiftapiserveroperator_04_roles.yaml
  manifests/00_clusteropenshiftapiserveroperator_05_serviceaccount.yaml
  manifests/00_clusteropenshiftapiserveroperator_06_deployment.yaml
Labels: approved, lgtm, size/L

#12 prevent hotlooping in operator
  pkg/operator/operator.go
Labels: approved, lgtm, size/S
