Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2018-10, with the labels that each got.

#15 update manifest filenames to conform to expected format
  manifests/0000_20_cluster-openshift-apiserver-operator_00_namespace.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_01_config.crd.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_02_config.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_03_configmap.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_04_roles.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#16 observe configuration from the cluster
  glide.lock
  pkg/apis/openshiftapiserver/v1alpha1/types.go
  pkg/apis/openshiftapiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/observe_config.go
  pkg/operator/starter.go
  pkg/operator/sync_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.pb.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.proto
  vendor/github.com/openshift/api/kubecontrolplane/v1/register.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/legacyconfig/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.proto
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/osin/v1/generated.pb.go
  vendor/github.com/openshift/api/osin/v1/generated.proto
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/webconsole/v1/generated.pb.go
  vendor/github.com/openshift/api/webconsole/v1/generated.proto
  vendor/github.com/openshift/api/webconsole/v1/types.go
  vendor/github.com/openshift/library-go/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/rbac.go
Labels: approved, lgtm, size/XXL

#19 only install on master nodes
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#20 tolerate any taint
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#21 remove operator config from payload
  bindata/v3.11.0/openshift-apiserver/operator-config.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#23 ensure operator config exists on start
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#24 fix apiservice registration update
  glide.lock
  vendor/github.com/openshift/api/authorization/OWNERS
  vendor/github.com/openshift/api/oauth/OWNERS
  vendor/github.com/openshift/api/security/OWNERS
  vendor/github.com/openshift/api/user/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
Labels: approved, lgtm, size/S

#28 stop managing the network apis
  pkg/operator/sync_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#29 bump library-go
  glide.lock
  pkg/operator/operator.go
  pkg/operator/sync_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/L

#30 don't manage apiservices until daemonset is up
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/sync_openshiftapiserver_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#25 add image-references
  manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#32 read etcd endpoint information
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#33 use proper set nested function
  pkg/operator/observe_config.go
Labels: approved, lgtm, size/XS

#35 fix deployment env
  manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#34 simple development flow
  README.md
Labels: approved, lgtm, size/S

#37 add ClusterOperator status
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/.travis.yml
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/hack/verify-golint.sh
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/L

#40 Bump deps
  glide.lock
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/hack/update-codegen.sh
  vendor/github.com/openshift/library-go/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/manifest.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/flag_test.go
Labels: approved, lgtm, size/XXL
