Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2018-11, with the labels that each got.

#41 Observe internalregistry hostname
  glide.lock
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/pkg/profile/.travis.yml
Labels: approved, lgtm, size/L

#49 move to operator specific namespace
  manifests/0000_20_cluster-openshift-apiserver-operator_00_namespace.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_03_configmap.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_04_roles.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_06_service.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, size/S

#45 pick up correct source of etcd connection info
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#55 Use openshift-apiserver container name for easier debugging
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#52 Update namespace in README.md
  README.md
Labels: approved, lgtm, size/XS

#58 Fix metric name
  pkg/version/version.go
Labels: approved, lgtm, size/XS

#59 use host-etcd service
  pkg/operator/configobservation/etcd/observe_etcd.go
Labels: approved, lgtm, size/S

#54 add additional imageconfig api field handling
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/images/OWNERS
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/images/observe_images_test.go
Labels: approved, lgtm, size/L

#65 Quickfix: increase pod readiness timeout
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#70 remove flapping config observation
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: approved, lgtm, size/XS

#72 bump library go to get events and fix cluster status
  glide.lock
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/images/observe_images_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller_test.go
Labels: approved, lgtm, size/XXL
