Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2018-12, with the labels that each got.

#76 Shorten config resource name
  bindata/v3.11.0/openshift-apiserver/cm.yaml
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#73 make daemonset pods node critical priority
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#78 Bump library go
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller_test.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper_unsupported.go
Labels: approved, lgtm, size/L

#63 Configure routing subdomain
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/ingresses/observe_ingresses.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#68 report Pending & Available status
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/S

#79 update for status
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/M

#74 operator: wait for spec.observedConfig to be fill before installing
  pkg/operator/workload_controller.go
Labels: approved, lgtm, size/XS

#62 force rollout on input change managed by a different controller
  pkg/operator/detectinputchange/as_configmap.go
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/L

#83 use library-go for hashing
  glide.lock
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_networking_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/L

#84 add memory request to openshift-apiserver and operator pods
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#88 fix configobserver failing status
  glide.lock
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
Labels: approved, lgtm, size/XL

#85 add clusteroperator resource to CVO payload
  manifests/0000_20_cluster-openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#91 Revert "add clusteroperator resource to CVO payload"
  manifests/0000_20_cluster-openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#89 copy cluster image CAs to api server configmap
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workload_controller.go
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#93 fix the progressing check
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#94 add progressing status unit test and updated messages
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, lgtm, size/L

#97 add service monitor resources for operator
  manifests/0000_20_cluster-openshift-apiserver-operator_00_namespace.yaml
  manifests/0000_20_cluster-openshift-apiserver-operator_06_service.yaml
  manifests/0000_90_cluster-openshift-apiserver-operator_01_prometheusrole.yaml
  manifests/0000_90_cluster-openshift-apiserver-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_cluster-openshift-apiserver-operator_03_servicemonitor.yaml
Labels: approved, lgtm, size/M

#99 handle err when extracting previous config
  pkg/operator/configobservation/images/observe_images.go
Labels: approved, lgtm, size/S

#98 Set terminationGracePeriodSeconds for enough graceful termination time
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS
