Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-12, with the labels that each got.

#272 Bug 1779237: bump(library-go): encryption: cope with missing revisions on upgrade
  glide.lock
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/revisionedpod.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/revisionedpod_test.go
  vendor/github.com/spf13/cobra/.circleci/config.yml
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/args_test.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completions_test.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/cobra/cmd/add.go
  vendor/github.com/spf13/cobra/cobra/cmd/add_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/golden_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/init.go
  vendor/github.com/spf13/cobra/cobra/cmd/init_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/project.go
  vendor/github.com/spf13/cobra/cobra/cmd/project_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/root.go
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/main.go.golden
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/root.go.golden
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/test.go.golden
  vendor/github.com/spf13/cobra/cobra/tpl/main.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_test.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs_test.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs_test.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs_test.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/powershell_completions_test.go
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/github.com/spf13/cobra/zsh_completions_test.go
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/bytes_test.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/flag_test.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int_test.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/string_to_string_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#259 Bug 1716835: Hooking Image Registry internal service certificates
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#274 Replace --{minimal-shutdown -> shutdown-delay}-duration
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#277 Bug 1781574: Fix panic in workload controller
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#282 update for library-go condition fixes.
  go.mod
  go.sum
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/gonum/matrix/gendoc.go
  vendor/github.com/openshift/api/apps/v1/generated.proto
  vendor/github.com/openshift/api/apps/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/glide.lock
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/inertia.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#279 [release-4.3] Bug 1781577: Fix panic in workload controller
  glide.lock
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/apps/v1/generated.proto
  vendor/github.com/openshift/api/apps/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/library-go/pkg/authentication/bootstrapauthenticator/bootstrap.go
  vendor/github.com/openshift/library-go/pkg/authentication/bootstrapauthenticator/bootstrap_test.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
