Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-02, with the labels that each got.

#138 bump library-go
  glide.lock
  vendor/github.com/openshift/library-go/pkg/assets/create/OWNERS
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/0000_10_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/00_openshift-kube-apiserver-ns.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/configmap-aggregator-client-ca.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/operator-config.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/testdata/secret-aggregator-client.yaml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/XXL

#139 depend on cluster-config-operator
  manifests/0000_61_openshift-apiserver-operator_02_project_config_crd.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/images/observe_images_test.go
  pkg/operator/configobservation/ingresses/observe_ingresses.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/configobservation/project/observe_projects.go
  pkg/operator/configobservation/project/observe_projects_test.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, lgtm, size/M

#130 Configure auditing
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#137 update to manage versions correctly
  manifests/0000_61_openshift-apiserver-operator_03_version-mapping.yaml
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, lgtm, size/M

#112 set cpu request for pod and operator
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#144 ensure we rollout when image pull spec changes
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#147 targetconfigcontroller: emit warning when management state is set to unknown value
  pkg/operator/workloadcontroller/workload_controller.go
Labels: approved, lgtm, size/XS

#149 set project template reference namespace
  pkg/cmd/resourcegraph/resourcegraph.go
  pkg/operator/configobservation/project/observe_projects.go
  pkg/operator/configobservation/project/observe_projects_test.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#151 remove artificial rate limits
  glide.lock
  pkg/operator/finalizer_controller.go
  pkg/operator/workloadcontroller/workload_controller.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/main.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/L

#152 fix file content detection race
  glide.lock
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
Labels: approved, lgtm, size/L

#153 switch image pull policy to if not present
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#150 Set openshift-apiserver privileged for audit to be able to write to /var/log/openshift-apiserver
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#157 bump to fix status reporting
  glide.lock
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/golang.org/x/tools/cmd/golsp/main.go
  vendor/golang.org/x/tools/cmd/guru/what.go
  vendor/golang.org/x/tools/go/packages/golist.go
Labels: approved, lgtm, size/L
