Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-01, with the labels that each got.

#102 add cluster operator to payload
  manifests/0000_20_openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#106 tighten names
  bindata/v3.11.0/openshift-apiserver/operator-config.yaml
  glide.lock
  manifests/0000_20_openshift-apiserver-operator_08_clusteroperator.yaml
  pkg/operator/generic_client.go
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workload_controller.go
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workload_controller_openshiftapiserver_v311_00_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_identityprovider.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/helpers/general.go
  vendor/github.com/openshift/library-go/pkg/config/helpers/general_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/backingresource/manifests/installer-sa.yaml
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/common/test_utils.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/XXL

#105 force clear the kube finalizer when kube resources are gone
  pkg/operator/finalizer_controller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#107 wait for kubeapiserver to be ready
  pkg/operator/workload_controller.go
Labels: approved, lgtm, size/S

#109 watch daemonsets, not deployments
  pkg/operator/workload_controller.go
Labels: approved, lgtm, size/XS

#110 add better messages
  glide.lock
  pkg/operator/workload_controller_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XL

#111 fix early rotation and excessive writes
  glide.lock
  pkg/operator/generic_client.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go.go
Labels: approved, lgtm, size/XXL

#113 explicitly list metrics port as first containerPort
  manifests/0000_20_openshift-apiserver-operator_07_deployment.yaml
Labels: approved, lgtm, size/XS

#117 manifests: add project config crd
  manifests/0000_20_openshift-apiserver-operator_02_project_config_crd.yaml
Labels: approved, lgtm, size/S

#118 project: fix project config observation
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/project/observe_projects.go
  pkg/operator/configobservation/project/observe_projects_test.go
Labels: approved, lgtm, size/S

#121 move openshift apiserver later in CVO payload
  manifests/0000_61_openshift-apiserver-operator_00_namespace.yaml
  manifests/0000_61_openshift-apiserver-operator_01_config.crd.yaml
  manifests/0000_61_openshift-apiserver-operator_02_project_config_crd.yaml
  manifests/0000_61_openshift-apiserver-operator_03_configmap.yaml
  manifests/0000_61_openshift-apiserver-operator_04_roles.yaml
  manifests/0000_61_openshift-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_61_openshift-apiserver-operator_06_service.yaml
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  manifests/0000_61_openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#123 fix cache mutation issue and version reporting
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/Makefile
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/hack/update-codegen.sh
  vendor/github.com/openshift/client-go/operator/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/interface.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/interface.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/openshiftapiserver.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/core_getters.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XXL

#125 add a check that actually attempts to hit the openshift api discovery
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/apigroup.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, lgtm, size/M

#126 set the explicit ca bundles
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, size/M

#128 add related apiservices
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/apigroup.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#127 support changing loglevel
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/S

#122 Fix log message in the ingress config observer
  pkg/operator/configobservation/ingresses/observe_ingresses.go
Labels: approved, lgtm, size/XS

#120 ingress: add event to ingress observer when domain change
  pkg/operator/configobservation/ingresses/observe_ingresses.go
  pkg/version/version.go
Labels: approved, lgtm, size/S

#132 Switch to openshift/api API
  Makefile
  bindata/v3.11.0/openshift-apiserver/operator-config.yaml
  glide.lock
  manifests/0000_61_openshift-apiserver-operator_01_config.crd.yaml
  pkg/apis/openshiftapiserver/install.go
  pkg/apis/openshiftapiserver/v1alpha1/doc.go
  pkg/apis/openshiftapiserver/v1alpha1/register.go
  pkg/apis/openshiftapiserver/v1alpha1/types.go
  pkg/apis/openshiftapiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/fake/fake_openshiftapiserver_client.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/fake/fake_openshiftapiserveroperatorconfig.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/openshiftapiserver_client.go
  pkg/generated/clientset/versioned/typed/openshiftapiserver/v1alpha1/openshiftapiserveroperatorconfig.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/openshiftapiserver/interface.go
  pkg/generated/informers/externalversions/openshiftapiserver/v1alpha1/interface.go
  pkg/generated/informers/externalversions/openshiftapiserver/v1alpha1/openshiftapiserveroperatorconfig.go
  pkg/generated/listers/openshiftapiserver/v1alpha1/expansion_generated.go
  pkg/generated/listers/openshiftapiserver/v1alpha1/openshiftapiserveroperatorconfig.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/operatorclient/operatorclient.go
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/github.com/openshift/library-go/pkg/serviceability/serviceability.go
Labels: approved, lgtm, size/XXL
