Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-03, with the labels that each got.

#108 when forcing a rolling update, emit event with reason
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/L

#160 operator: use proto client for api registration client
  pkg/operator/starter.go
Labels: approved, lgtm, size/XS

#154 Set minimal-shutdown-duration to 3s
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#163 use dynamic reloading of certs to avoid rolling out new deployment versions
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#166 workload: fix bad formatting in event message
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#167 cmd: fix operator component name
  pkg/cmd/operator/cmd.go
Labels: approved, lgtm, size/XS

#162 manifests: system-cluster-critical priority for operator
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
Labels: approved, lgtm, size/XS

#159 Set audit directory to be 0700
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/S

#161 minor fitting to set versions for our operator
  manifests/0000_61_openshift-apiserver-operator_03_version-mapping.yaml
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  manifests/0000_61_openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/S

#169 fix up owners files
  pkg/operator/configobservation/images/OWNERS
Labels: approved, lgtm, size/XS
