Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-09, with the labels that each got.

#229 Bug 1746942: Fix setting the log level
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#231 Bug 1747260: Fix trusted-ca-bundle CM syncing
  manifests/0000_30_openshift-apiserver-operator_03_trusted_ca_cm.yaml
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#232 Bug 1747260: Last (?) fix to trusted-ca CM syncing
  Dockerfile.rhel7
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
