Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-06, with the labels that each got.

#205 Bug 1718052: Do not log OAuth tokens in audit logs
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#204 operator: report more details when api check fail
  pkg/operator/workloadcontroller/apigroup.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/S

#207 bindata: monitor openshift-apiserver namespace
  bindata/v3.11.0/openshift-apiserver/ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#208 manifests: add servicemonitor for openshift apiserver
  manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm, size/M

#209 manifests: fix apiVersion for operator config
  manifests/0000_30_openshift-apiserver-operator_03_configmap.yaml
Labels: approved, lgtm, size/XS
