Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-11, with the labels that each got.

#247 uses e2e encryption test cases from library-go
  glide.lock
  test/e2e-encryption/encryption_test.go
  test/e2e/operator_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
  test/library/encryption/scenarios.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/testing/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/events/eventstesting/recorder_wrapper.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/github.com/openshift/library-go/test/library/encryption/scenarios.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra/cmd/add.go
  vendor/github.com/spf13/cobra/cobra/cmd/add_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/init.go
  vendor/github.com/spf13/cobra/cobra/cmd/init_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/project.go
  vendor/github.com/spf13/cobra/cobra/cmd/project_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/root.go
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/main.go.golden
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/root.go.golden
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/test.go.golden
  vendor/github.com/spf13/cobra/cobra/tpl/main.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_test.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/powershell_completions_test.go
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/github.com/spf13/cobra/zsh_completions_test.go
Labels: approved, lgtm, size/XXL

#249 verifies encryption config and prints events from the operator's ns
  glide.lock
  test/e2e-encryption/encryption_test.go
  test/e2e/operator_test.go
  test/library/encryption/assertion.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/github.com/openshift/library-go/test/library/encryption/scenarios.go
Labels: approved, lgtm, size/L

#248 Bug 1767156: Fix "Multipleavailable" reason in the code
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#250 auditConfig: Log write operations of Identities with RequestResponse
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#119 update README to provide more info about operator
  README.md
Labels: approved, lgtm, size/M

#256 Fix metrics
  manifests/0000_90_openshift-apiserver-operator_03_servicemonitor.yaml
  pkg/version/version.go
Labels: approved, lgtm, size/S

#253 Bug 1735509: monitoring: move service monitor RBAC rules to manifests/
  manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#251 bump(library-go): get encryption in-process migrator error handling
  glide.lock
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/samples/install.go
  vendor/github.com/openshift/api/samples/v1/0000_10_samplesconfig.crd.yaml
  vendor/github.com/openshift/api/samples/v1/doc.go
  vendor/github.com/openshift/api/samples/v1/generated.pb.go
  vendor/github.com/openshift/api/samples/v1/generated.proto
  vendor/github.com/openshift/api/samples/v1/register.go
  vendor/github.com/openshift/api/samples/v1/types_config.go
  vendor/github.com/openshift/api/samples/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/samples/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics_test.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/errors.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess_test.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/types.go
  vendor/github.com/openshift/library-go/test/e2e-encryption/encryption_test.go
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra/README.md
  vendor/github.com/spf13/cobra/cobra/cmd/add.go
  vendor/github.com/spf13/pflag/.travis.yml
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/float32_slice.go
  vendor/github.com/spf13/pflag/float32_slice_test.go
  vendor/github.com/spf13/pflag/float64_slice.go
  vendor/github.com/spf13/pflag/float64_slice_test.go
  vendor/github.com/spf13/pflag/int32_slice.go
  vendor/github.com/spf13/pflag/int32_slice_test.go
  vendor/github.com/spf13/pflag/int64_slice.go
  vendor/github.com/spf13/pflag/int64_slice_test.go
  vendor/github.com/spf13/pflag/ip_slice.go
Labels: approved, lgtm, size/XXL

#258 Add manifest annotations for hosted deployment exclusions
  manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
  manifests/0000_30_openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#260 use upstream cluster authentication config
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/cmd/resourcegraph/resourcegraph.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#262 Bug 1774907: fix ns for prometheus-k8s rolebinding
  manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#265 adds scaffolding for e2e perf/load encryption tests
  Makefile
  test/e2e-encryption-perf/encryption_perf_test.go
Labels: approved, lgtm, size/S

#266 Bug 1737322: Stop logging secrets
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/change_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/limit_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/scope_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL
