Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-04, with the labels that each got.

#172 Debug handler
  glide.lock
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm, size/L

#175 Upgrade fix
  glide.lock
  glide.yaml
  manifests/0000_61_openshift-apiserver-operator_03_version-mapping.yaml
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  manifests/0000_61_openshift-apiserver-operator_08_clusteroperator.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/quota/v1/generated.proto
  vendor/github.com/openshift/api/quota/v1/types.go
  vendor/github.com/openshift/api/tools/genswaggertypedocs/swagger_type_docs.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/spf13/cobra/.circleci/config.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/args_test.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completions_test.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/cobra/cmd/golden_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/init.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_test.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs_test.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs_test.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs_test.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/.travis.yml
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/bytes_test.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/flag_test.go
  vendor/github.com/spf13/pflag/float32_slice.go
  vendor/github.com/spf13/pflag/float32_slice_test.go
  vendor/github.com/spf13/pflag/float64_slice.go
  vendor/github.com/spf13/pflag/float64_slice_test.go
  vendor/github.com/spf13/pflag/int32_slice.go
  vendor/github.com/spf13/pflag/int32_slice_test.go
  vendor/github.com/spf13/pflag/int64_slice.go
  vendor/github.com/spf13/pflag/int64_slice_test.go
  vendor/github.com/spf13/pflag/ip_slice.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int_test.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/string_to_string_test.go
Labels: approved, lgtm, size/XXL

#176 add test-e2e make target
  Makefile
  test/e2e/operator_test.go
  test/library/client.go
Labels: approved, lgtm, size/M

#178 metrics were flaky
  glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metrics/monitor.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metrics/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
Labels: approved, lgtm, size/L

#180 report failures to pod status
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#181 Switch openshift/oas-o to go1.11
  .travis.yml
Labels: approved, lgtm, size/XS

#182 Switch to go1.11
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#184 update to degraded condition
  glide.lock
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
  vendor/github.com/gobuffalo/envy/SHOULDERS.md
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/envy_test.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go
Labels: approved, lgtm, size/XL

#185 switch to pull etcd info from openshift-config
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, lgtm, size/S

#187 wait for caches to sync
  glide.lock
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/XL

#186 Use the CVO to create operator config
  bindata/v3.11.0/openshift-apiserver/operator-config.yaml
  manifests/0000_61_openshift-apiserver-operator_01_operator.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#188 make observation func more tolerant
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#189 make missing resources
  bindata/v3.11.0/openshift-apiserver/etcd-ns.yaml
  bindata/v3.11.0/openshift-apiserver/etcd-service.yaml
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#190 shorten leader election
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/S

#191 update deployment for upgrade and install-gather
  manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
Labels: approved, lgtm, size/XS

#192 permanently swap to openshift-etcd
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#194 emit events for version changes
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/int32.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/XL

#193 stop creating resources for etcd
  bindata/v3.11.0/openshift-apiserver/etcd-ns.yaml
  bindata/v3.11.0/openshift-apiserver/etcd-service.yaml
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#195 Add node-selector annotation to namespace
  bindata/v3.11.0/openshift-apiserver/ns.yaml
  manifests/0000_61_openshift-apiserver-operator_00_namespace.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: size/S

#196 Move openshift-apiserver to 0000_30 (secondary API runlevel)
  manifests/0000_30_openshift-apiserver-operator_00_namespace.yaml
  manifests/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  manifests/0000_30_openshift-apiserver-operator_01_operator.cr.yaml
  manifests/0000_30_openshift-apiserver-operator_03_configmap.yaml
  manifests/0000_30_openshift-apiserver-operator_04_roles.yaml
  manifests/0000_30_openshift-apiserver-operator_05_serviceaccount.yaml
  manifests/0000_30_openshift-apiserver-operator_06_service.yaml
  manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
  manifests/0000_30_openshift-apiserver-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#197 manifests: bump loglevel of operator to normal
  manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
Labels: approved, lgtm, size/XS
