Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-08, with the labels that each got.

#220 Bug 1737683: bump (*) to observe Proxy status instead of spec
  glide.lock
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/k8s.io/component-base/Godeps/Godeps.json
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/k8s.io/klog/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/k8s.io/klog/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/klogr/main.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/k8s.io/klog/klogr/klogr_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#225 Sort the EnvVar from Proxy string map
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/XS

#223 use non-static operator client
  pkg/operator/starter.go
Labels: approved, lgtm, size/XS

#228 Bug 1746375: Revert use of watchdog for trusted-ca-bundle
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  cmd/cluster-openshift-apiserver-operator/main.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#222 fix make images
  Makefile
Labels: approved, lgtm, size/S
