Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2019-10, with the labels that each got.

#236 add correct label to ds config initContainer
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#238 encryption: remove key secret finalizer before pruning
  pkg/operator/prunecontroller/prune_controller.go
Labels: approved, lgtm, size/M

#239 scaffolding for encryption e2e tests
  Makefile
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/S

#240 bumps dependencies
  glide.lock
  vendor/github.com/openshift/api/authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/0000_10_consoleclidownload.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consoleexternalloglink.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolelink.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolenotification.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/hack/verify-crds.sh
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/library-go/test/e2e-encryption/encryption_test.go
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
  vendor/github.com/openshift/library-go/test/library/encryption/etcd_client.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
Labels: approved, lgtm, size/XXL

#244 points encryption config observer to an encryption config file
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Labels: approved, lgtm, size/XS

#243 e2e tests for etcd encryption
  glide.lock
  test/e2e-encryption/encryption_test.go
  test/e2e-encryption/main_test.go
  test/e2e/operator_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
  test/library/encryption/scenarios.go
  vendor/github.com/pmezard/go-difflib/.travis.yml
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/README.md
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/pmezard/go-difflib/difflib/difflib_test.go
  vendor/github.com/stretchr/testify/.gitignore
  vendor/github.com/stretchr/testify/.travis.gofmt.sh
  vendor/github.com/stretchr/testify/.travis.gogenerate.sh
  vendor/github.com/stretchr/testify/.travis.govet.sh
  vendor/github.com/stretchr/testify/.travis.yml
  vendor/github.com/stretchr/testify/Gopkg.lock
  vendor/github.com/stretchr/testify/Gopkg.toml
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/_codegen/main.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/assertions_test.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions_test.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions_test.go
  vendor/github.com/stretchr/testify/doc.go
  vendor/github.com/stretchr/testify/go.mod
  vendor/github.com/stretchr/testify/go.sum
  vendor/github.com/stretchr/testify/http/doc.go
  vendor/github.com/stretchr/testify/http/test_response_writer.go
  vendor/github.com/stretchr/testify/http/test_round_tripper.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/mock/mock_test.go
  vendor/github.com/stretchr/testify/package_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/forward_requirements_test.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/stretchr/testify/require/requirements_test.go
  vendor/github.com/stretchr/testify/suite/doc.go
  vendor/github.com/stretchr/testify/suite/interfaces.go
  vendor/github.com/stretchr/testify/suite/suite.go
  vendor/github.com/stretchr/testify/suite/suite_test.go
Labels: approved, lgtm, size/XXL
