Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-04, with the labels that each got.

#347 encryption provider
  go.mod
  go.sum
  pkg/operator/deploynodeprovider.go
  pkg/operator/encryptionprovider/encryptionprovider.go
  pkg/operator/encryptionprovider/encryptionprovider_test.go
  pkg/operator/oauthapiencryptioncontroller/oauthapiencryptioncontroller.go
  pkg/operator/oauthapiencryptioncontroller/oauthapiencryptioncontroller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/deploynodeprovider.go
  vendor/modules.txt
Labels: approved, lgtm

#284 DEVEXP-424: Mounting node pull secrets
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/S

#352 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#353 Fix build_info reporting
  go.mod
  go.sum
  pkg/version/version.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/encryptionconfig/secret.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/secrets/secrets.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: approved, lgtm

#355 Bug 1828835: remove duplicate migration informer start
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#354 Bug 1827050: Update to use revised ApplyDeployment
  pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
