Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-01, with the labels that each got.

#276 separate finalizer cleanup controller to allow re-use
  pkg/operator/nsfinalizercontroller/finalizer_controller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#275 create apiservice controller
  go.mod
  pkg/operator/apiservicecontroller/apigroup.go
  pkg/operator/apiservicecontroller/apiservice_controller.go
  pkg/operator/apiservicecontroller/apiservice_controller_test.go
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/apigroup.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, lgtm, size/XL

#286 replace verbosity based on string substitution for ease
  bindata/v3.11.0/openshift-apiserver/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#287 vastly simplify the image registry trust configmap
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#285 switch to including hashes in annotation instead of ordered plumbing
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/M

#289 merge hashing resources for forced DS rollouts
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#273 Specify "bindNetwork: tcp" so apiserver will work on IPv6 single-stack
  bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#297 bump(library-go) changes the next empty encryption key's name for encryption e2e test
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#288 simplify logic to get the proxy configmap
  bindata/v3.11.0/openshift-apiserver/trusted_ca_cm.yaml
  go.mod
  go.sum
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  vendor/github.com/prometheus/client_golang/prometheus/build_info.go
  vendor/github.com/prometheus/client_golang/prometheus/build_info_pre_1.12.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/prometheus/procfs/internal/fs/fs.go
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/mountinfo.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_environ.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#290 split apiserver controllers initialization to a separate module
  pkg/operator/apiservercontrollerset/apiservercontrollerset.go
  pkg/operator/apiservicecontroller/apiservice_controller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#294 OAuth related API Services can be managed/served by an external server/operator
  go.mod
  go.sum
  pkg/operator/apiservercontrollerset/apiservercontrollerset.go
  pkg/operator/apiservicecontroller/apigroup.go
  pkg/operator/apiservicecontroller/apiservice_controller.go
  pkg/operator/apiservicecontroller/apiservice_controller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#303 bug 1792386: set the operand version and make the CVO wait
  manifests/0000_30_openshift-apiserver-operator_08_clusteroperator.yaml
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#305 picks kube 1.17.1
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/interface.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#291 encryption: switch to kube-storage-version-migrator
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/clients/informer/factory.go
  vendor/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/clients/informer/generic.go
  vendor/github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/clients/informer/migration/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#304 make static resource controller you simply pass manifests to
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/core_getters.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
