Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-12, with the labels that each got.

#416 updates encryption related components so that CAO can start manage its own encryption configuration
  Makefile
  go.mod
  go.sum
  pkg/operator/encryptionprovider/encryptionprovider.go
  pkg/operator/encryptionprovider/encryptionprovider_test.go
  pkg/operator/oauthapiencryption/oauthapiencryptioncontroller.go
  pkg/operator/oauthapiencryption/oauthapiencryptioncontroller_test.go
  pkg/operator/revisionpoddeployer/deployers.go
  pkg/operator/starter.go
  test/e2e-encryption-perf/encryption_perf_test.go
  test/e2e-encryption/encryption_test.go
  test/e2e/operator_test.go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauth_client.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthaccesstoken.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthauthorizetoken.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthclient.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/oauthclientauthorization.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/statemachine/transition.go
  vendor/modules.txt
Labels: approved, lgtm

#422 wait for storage urls before installing the api server
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go
  pkg/operator/workload/workload_openshiftapiserver_v311_00_sync_test.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/etcd/observe_etcd_endpoints.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#323 Bug 1806918: remove run-level=1 from openshift-apiserver NS
  bindata/v3.11.0/openshift-apiserver/ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#330 Bug 1806918: remove run-level=1 from openshift-apiserver-operator NS
  manifests/0000_30_openshift-apiserver-operator_00_namespace.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#421 Bug 1907956: connectivitycheckcontroller: bump
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/etcd/observe_etcd_endpoints.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
