Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-05, with the labels that each got.

#360 Bug 1832220: operator: add openshift-etcd-operator namespace to related objects
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#362 Bug 1795163: openshift-apiserver operator not available when used for single node cluster (CRC)
  pkg/operator/starter.go
  pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#356 Bug 1834852: Add make target to run operator with telepresence
  .gitignore
  Makefile
  glide.lock
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#365 Bug 1837353: encryption: don't degrade when daemonset is not found
  pkg/operator/dsnodeprovider.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#364 Bug 1836927: Prefer etcd endpoints configmap for storage URL discovery
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcdendpoints/OWNERS
  pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints.go
  pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints_test.go
  pkg/operator/configobservation/etcdobserver/OWNERS
  pkg/operator/configobservation/interfaces.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
