Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-02, with the labels that each got.

#307 Bug 1798215: Add a new label 'apiserver' to identify the source
  manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#309 Bug 1801154: manifests/: Throw away unused high cardinality apiserver duration buckets
  manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#311 Bug 1803922: encryption: don't degrade when daemonset is not found
  pkg/operator/dsnodeprovider.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#308 Move default config to its own path
  README.md
  bindata/v3.11.0/config/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, lgtm, size/L

#312 Bug 1805254: openshift-apiserver should directly use the host-etcd IPs
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/etcdobserver/observe_etcd.go
  pkg/operator/configobservation/etcdobserver/observe_etcd_test.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#317 waits for extension-apiserver-authentication before rolling out a new version
  pkg/operator/workloadcontroller/workload_controller.go
Labels: approved, lgtm, size/S

#320 Bug 1806671: openshift-apiserver should never use the bootstrap etcd member
  pkg/operator/configobservation/etcdobserver/observe_etcd.go
  pkg/operator/configobservation/etcdobserver/observe_etcd_test.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#313 bug 1804717: Switch to managing openshift-apiserver pods with a deployment
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/apiservicecontroller/apiservice_controller_test.go
  pkg/operator/deploynodeprovider.go
  pkg/operator/nsfinalizercontroller/finalizer_controller.go
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#321 Degrade on no host etcd endpoints
  pkg/operator/configobservation/etcdobserver/observe_etcd.go
  pkg/operator/configobservation/etcdobserver/observe_etcd_test.go
Labels: approved, lgtm, size/XS

#324 bug 1804717: Cleanup switch to managing openshift-apiserver pods with a deployment
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/apiservicecontroller/apiservice_controller.go
  pkg/operator/deploynodeprovider.go
  pkg/operator/prunecontroller/prune_controller.go
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
