Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-03, with the labels that each got.

#327 waits for requestheader-client-ca-file in extension-apiserver-authentication before rolling out a new version
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
Labels: approved, lgtm, size/S

#329 doesn't allow for specifying the worker count number for workload controller
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
Labels: approved, lgtm, size/XS

#328 [release-4.4] Bug 1795163: waits for extension-apiserver-authentication before rolling out a new version
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#314 Bug 1805388: Cleanup 4.4 deployment on downgrade to 4.3
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#331 Bug 1808568: Fix rollout strategy to never run more than one pod per node
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
  pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#326 [release-4.3] Bug 1809532: waits for requestheader-client-ca-file in extension-apiserver-authentication before rolling out a new version
  pkg/operator/starter.go
  pkg/operator/workloadcontroller/workload_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#335 makes ObserveConfigController to react on config updates.
  go.mod
  go.sum
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#336 brings APIServicesToManage to OAS
  pkg/operator/apiservice/apiservice_openshiftapiserver_sync.go
  pkg/operator/apiservice/apiservice_openshiftapiserver_sync_test.go
  pkg/operator/starter.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#337 bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go
  vendor/modules.txt
Labels: approved, lgtm

#338 Bug 1814618: storage urls observer: prevent event/log spam
  pkg/operator/configobservation/etcdobserver/observe_etcd.go
Labels: approved, bugzilla/valid-bug, lgtm

#339 Bug 1814621: storage urls observer: prevent event/log spam
  pkg/operator/configobservation/etcdobserver/observe_etcd.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#334 Bug 1812583: Normalize CPU requests on masters
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#343 starter: fix graceful operator shutdown
  pkg/operator/starter.go
Labels: approved, lgtm

#344 OAuthAPIServerController
  pkg/operator/oauthapiencryptioncontroller/oauthapiencryptioncontroller.go
  pkg/operator/oauthapiencryptioncontroller/oauthapiencryptioncontroller_test.go
Labels: approved, lgtm

#346 takes encryption controllers from apiservercontrollerset
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, lgtm
