Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-10, with the labels that each got.

#388 Bug 1876167: disable openshift-apiserver connectivity checks
  go.mod
  go.sum
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/starter.go
  test/e2e/connectivity_check_test.go
  vendor/github.com/openshift/library-go/pkg/apps/deployment/status.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#398 flowschema for openshift apiserver and its operator
  manifests/0000_30_openshift-apiserver-operator_09_flowschema.yaml
Labels: approved, lgtm

#399 Updating ose-cluster-openshift-apiserver-operator builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#402 Bug 1876166: need to be able to disable kube-apiserver connectivity checks
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#400 Revert "connectivitycheckcontroller: disable by default"
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  test/e2e/connectivity_check_test.go
Labels: approved, lgtm

#404 bug 1888028: bump library-go to stop waiting on kube-apiserver availability
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#406 BUG 1888311: p&f: make oas SAR/TokenReview traffic exempt
  manifests/0000_30_openshift-apiserver-operator_09_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#407 connectivitycheckcontroller: disable by default
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  test/e2e/connectivity_check_test.go
Labels: approved, lgtm

#408 enable etcd latency metric
  manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
Labels: approved, lgtm

#409 Observe Ingress AppsDomain For Routing Domain Override
  go.mod
  go.sum
  pkg/operator/configobservation/ingresses/observe_ingresses.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/modules.txt
Labels: approved, lgtm

#397 Restrict log permissions
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm
