Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2020-08, with the labels that each got.

#376 connectivitycheckcontroller: sync w/ kube-apiserver improvements
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_template.go
  pkg/operator/starter.go
Labels: approved, lgtm

#379 avoid overlaping connectivity check names
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#377 connectivitycheckcontroller: check names should use node names
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#380 connectivitycheckcontroller: use generic controller
  go.mod
  go.sum
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_template.go
  vendor/modules.txt
Labels: approved, lgtm

#383 Bug 1871890: Bump coao to golang 1.14 to match kube
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#384 Bug 1870922: oc get PodNetworkConnectivityCheck -n openshift-apiserver has no resource
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  test/e2e/connectivity_check_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
