Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2021-04, with the labels that each got.

#440 expose pod information to oas container via env variables
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm

#442 extends shutdown delay duration to 10 seconds
  bindata/v3.11.0/config/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm

#437 Bug 1942725: explicitly allow apiserver pods to write to their root FS
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#443 Add management workload annotations
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  bindata/v3.11.0/openshift-apiserver/ns.yaml
  manifests/0000_30_openshift-apiserver-operator_00_namespace.yaml
  manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#446 Rename workload annotations
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm
