Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2023-07, with the labels that each got.

#542 Plumb featuregates to the openshift-apiserver
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/modules.txt
Labels: lgtm, approved

#544 AUTH-408: bindata: set required-scc
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, jira/valid-reference

#543 OCPBUGS-13346: dont log jwt tokens
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
