Repository openshift/cluster-openshift-apiserver-operator, pull requests merged in 2023-06, with the labels that each got.

#536 OCPBUGS-14010: increase timeout for probes
  bindata/v3.11.0/openshift-apiserver/deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#539 Add AES-GCM encryption tests
  Makefile
  go.mod
  go.sum
  test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
  test/e2e-encryption/encryption_test.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/modules.txt
Labels: lgtm, approved

#540 allow etcd healthcheck timeout closer to probe timeouts to avoid failing on slower etcd
  bindata/v3.11.0/config/defaultconfig.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved

#541 OCPBUGS-13763: dont log tokens
  go.mod
  go.sum
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
  vendor/github.com/openshift/library-go/test/library/encryption/assertion.go
  vendor/github.com/openshift/library-go/test/library/encryption/perf_scenarios.go
  vendor/github.com/openshift/library-go/test/library/encryption/scenarios.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
